Feature internationalization
NMP300/Ruby_on_Rails_practice pull request #2
Opened 2019-11-08 05:45 UTC by NMP300

Internationalized app.

2019-11-08 09:02 UTC, komagata requested changes

2019-11-08 09:02 UTC, komagata commented on app/assets/stylesheets/application.scss
> +@import "bootstrap";
最終行に改行がないようです〜

2019-11-08 09:02 UTC, komagata commented on app/controllers/books_controller.rb
>          format.json { render :show, status: :created, location: @book }
JSONを使う必要がなければ関連処理は削除しちゃってください〜

2019-11-08 09:02 UTC, komagata commented on app/views/books/_form.html.slim
> +
二行空いてるのが気になりますね。

2019-11-08 09:02 UTC, komagata commented on app/views/books/edit.html.slim
> += link_to "#{t'link.Back'}", books_path
最終行に改行が無いようです〜

2019-11-10 02:04 UTC, komagata commented on app/controllers/books_controller.rb
> +        format.html { redirect_to @book, notice: "#{t 'errors.messages.Book_was_successfully_created.'}" }
他のフォーマットに対応しないのであればrespond_to自体が必要ないです。

respond_toがどういう機能を持つのか調べてみると良いかもです。

2019-11-10 02:04 UTC, komagata commented on app/views/books/new.html.slim
> +  = link_to "#{t'link.Back'}", books_path
最終行に改行が無いようです。

2019-11-10 02:04 UTC, komagata commented on config/locales/carriewave/en.yml
> +      max_size_error: "File size should be less than %{max_size}"
最終行に改行が無いようです。

2019-11-10 02:04 UTC, komagata commented
エディターで自動的に最終行に改行が入るように設定したほうがいいとおもいます。

また、ローカルで確認したとしても、PRでレビュー依頼する時は必ずFiles changedを確認してから出す癖をつけた方がいいとおもいます。仕事でやっている人はみなそういう癖が自然についている気がします〜

2019-11-11 05:06 UTC, NMP300 commented on app/controllers/books_controller.rb
> +        format.html { redirect_to @book, notice: "#{t 'errors.messages.Book_was_successfully_created.'}" }
承知しました‼️

調べてみて、`respond_to`は`format.{形式}`で指定された形式で情報を返す機能だと分かりました‼️

2019-11-11 05:13 UTC, NMP300 commented
> エディターで自動的に最終行に改行が入るように設定したほうがいいとおもいます。

教えていただき、ありがとうございます。エディタの方設定しました↓
<img width="383" alt="スクリーンショット 2019-11-11 14 07 26" src="https://user-images.githubusercontent.com/51867807/68562352-a3e75200-048c-11ea-912d-4adcfe8b797a.png">

> また、ローカルで確認したとしても、PRでレビュー依頼する時は必ずFiles changedを確認してから出す癖をつけた方がいいとおもいます。仕事でやっている人はみなそういう癖が自然についている気がします〜

チェックの手間を増やしてしまい申し訳ありません💦🙇‍♂️
レビューしていただく方の負担を増やさないようにFile changedは必ず確認したいと思います🔥

そこで、1点質問なのですが、File changedを確認するとき、@komagataさんはどのような点に気をつけてらっしゃいますか？自分なりのチェックリストのようなものがあるのでしょうか？

私の場合、なんとなく確認しているだけの感じがしてしまって、気をつけて見ることができていない気がしたので、教えていただければ幸いです🙇‍♂️

2019-11-11 05:59 UTC, komagata commented
最終行の改行やインデント、不要なコメントなどはパッと見てわかるのでそれはチェックしています。

自分がPRを作る場合はそれ以前にコードフォーマットや最終行の改行はツールでやっているで気にしていないです。

自分のPRを作ったらFiles Changedでみて、全ての行をどういう意図で書いてるのかを自分の中で考えながらチェックしています。

ただViewはあんまりちゃんとチェックしてないです。

2019-11-11 06:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2019-11-11 06:30 UTC, NMP300 commented
なるほど🤔
教えていただきありがとうございます🙇‍♂️

自分の中で、ここをチェックした方が良いというチェックリストができていなかったので、とても参考になります‼️
教えていただいた項目を中心に注意深く自分のコードをチェックしていきたいと思います🔥

2019-11-11 06:32 UTC, merged