Feature user authentication
NMP300/Ruby_on_Rails_practice pull request #4
Opened 2019-11-19 06:40 UTC by NMP300

# What I did

- Introduced user authentication by devise.

2019-11-20 02:59 UTC, komagata requested changes

2019-11-20 02:59 UTC, komagata commented on app/helpers/users_helper.rb
> +module UsersHelper
実装がないものは削除しちゃってください〜

2019-11-20 08:25 UTC, NMP300 commented on app/helpers/users_helper.rb
> +module UsersHelper
ご指摘ありがとうございます🙇‍♂️
使用していなかったapp/helpersディレクトリと、deviseのメール関連に関するファイルを削除しました🙇‍♂️

2019-11-20 09:32 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2019-11-21 01:38 UTC, NMP300 commented
ありがとうございます‼️🙇‍♂️

2019-11-21 01:38 UTC, merged